### ISSUE TITLE
ERR_INPUT_TYPE_NOT_ALLOWED with example script

### ISSUE THREAD

**Issue by kbeerman** [sindresorhus/alfy#141]
Using:
Alfred version 4.5.1 with Powerpack
Node version 14.17.5 

After following all steps as described under Usage, when running the example workflow I get the following error in Alfred debugger:

```
Alfy[Script Filter] Queuing argument 'h'
Alfy[Script Filter] Script with argv 'h' finished
ERROR: Alfy[Script Filter] Code 1: internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_INPUT_TYPE_NOT_ALLOWED]: --input-type can only be used with string input via --eval, --print, or STDIN
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:813:13)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at Loader.import (internal/modules/esm/loader.js:177:28)
    at internal/modules/run_main.js:50:28
    at Object.loadESM (internal/process/esm_loader.js:68:11) {
  code: 'ERR_INPUT_TYPE_NOT_ALLOWED'
}
```
 
When I navigate to the workflow folder in terminal and run the javascript file with `node index.js {query}` I do get the expected result (JSON is returned).

**Comment by olliethomas1992** [comment]
I am experiencing the same issue.

Alfred 4.5.1 with Powerpack
Node: v14.16.0

**Comment by L3K0V** [comment]
Any workaround?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/alfy/releases/tag/v0.12.1
