### ISSUE TITLE
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader

### ISSUE THREAD

**Issue by leoGeorges** [sindresorhus/alfy#146]
Using `"alfy": "^0.12.1"` does not seem to be working and following error is shown in Alfred's debug console :

```
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:724:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:50:40)
    at link (internal/modules/esm/module_job.js:49:36) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
````

Reproduction:

_index.js_

```javascript
import alfy from 'alfy';

alfy.log(process.version);
```

_package.json_

```json
{
  "name": "user.workflow.1253dd5c-71c6-45b3-9ddc-49d5b88037ea",
  "version": "1.0.0",
  "description": "",
  "exports": "./index.js",
  "type": "module",
  "dependencies": {
    "alfy": "^0.12.1"
  },
  "engines": {
    "node": ">=16.0.0"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

**Comment by sindresorhus** [comment]
I just tried upgrading one of my Alfred workflows that use Alfy and it works fine for me: https://github.com/sindresorhus/alfred-npms/commit/ced041dcd11ae6998bee2be812940639f4877e55

**Comment by sindresorhus** [comment]
Make sure you're running Node.js 14.13 or later.

**Comment by flexbox** [comment]
Hey @leoGeorges 
If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨
