### ISSUE TITLE
Plist Error

### ISSUE THREAD

**Issue by vinkla** [sindresorhus/alfy#17]
I've made a copy of the `alfred-npms` package and I'm trying to use the same workflow for another API. Though, the error below is thrown.

```
TypeError: Cannot read property '1' of null
    at getVersion (/Users/vincent/Dropbox/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.EE45FE2B-0856-4D6E-AFC7-77DBEE8E52F6/node_modules/alfy/index.js:29:104)
    at Object.<anonymous> (/Users/vincent/Dropbox/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.EE45FE2B-0856-4D6E-AFC7-77DBEE8E52F6/node_modules/alfy/index.js:37:11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/vincent/Dropbox/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.EE45FE2B-0856-4D6E-AFC7-77DBEE8E52F6/index.js:2:14)
[2016-08-31 09:30:39][ERROR: input.scriptfilter] Code 1: /Users/vincent/Dropbox/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.EE45FE2B-0856-4D6E-AFC7-77DBEE8E52F6/node_modules/alfy/index.js:29
	return /<key>version<\/key>[\s\S]*<string>([\d.]+)<\/string>/.exec(fs.readFileSync(infoPlist, 'utf8'))[1];
	                                                                                                      ^
```

If I take the line below and remove the `[1]` in the end…

```
return /<key>version<\/key>[\s\S]*<string>([\d.]+)<\/string>/.exec(fs.readFileSync(infoPlist, 'utf8'))[1];
```

…it works. Then my package is executed as expected. What am I doing wrong? Any thoughts?

**Comment by SamVerschueren** [comment]
`alfred-npms` uses `alfy@0.2x`. The logic for extracting the version was removed in `alfy@0.3.x` so I suggest upgrading and it should work.

**Comment by vinkla** [comment]
Aah, I see. Thanks @SamVerschueren!
