### ISSUE TITLE
Issue Updating Alfy Workflow

### ISSUE THREAD

**Issue by vinkla** [sindresorhus/alfy#68]
Yesterday we released a new version of the [`alfred-packagist`](https://github.com/vinkla/alfred-packagist). When we tried to update the package locally with `npm i -g alfred-packagist` we get the following error:

```
> alfred-packagist@1.0.0 preuninstall /usr/local/lib/node_modules/alfred-packagist
> alfy-cleanup

{ Error: Command failed: alfred-unlink
module.js:529
    throw err;
    ^

Error: Cannot find module './'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/alfred-packagist/node_modules/.bin/alfred-unlink:3:20)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)

    at Promise.all.then.arr (/usr/local/lib/node_modules/alfred-packagist/node_modules/execa/index.js:201:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'module.js:529\n    throw err;\n    ^\n\nError: Cannot find module \'./\'\n    at Function.Module._resolveFilename (module.js:527:15)\n    at Function.Module._load (module.js:476:23)\n    at Module.require (module.js:568:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/usr/local/lib/node_modules/alfred-packagist/node_modules/.bin/alfred-unlink:3:20)\n    at Module._compile (module.js:624:30)\n    at Object.Module._extensions..js (module.js:635:10)\n    at Module.load (module.js:545:32)\n    at tryModuleLoad (module.js:508:12)\n    at Function.Module._load (module.js:500:3)\n',
  failed: true,
  signal: null,
  cmd: 'alfred-unlink',
  timedOut: false }
npm WARN lifecycle alfred-packagist@1.0.0~preuninstall: continuing anyway alfred-packagist@1.0.0 preuninstall: `alfy-cleanup`
npm WARN lifecycle Exit status 1
npm ERR! path /usr/local/lib/node_modules/alfred-packagist/node_modules/.bin/rimraf
npm ERR! code EEXIST
npm ERR! Refusing to delete /usr/local/lib/node_modules/alfred-packagist/node_modules/.bin/rimraf: is outside /usr/local/lib/node_modules/alfred-packagist/node_modules/rimraf and not a link
npm ERR! File exists: /usr/local/lib/node_modules/alfred-packagist/node_modules/.bin/rimraf
npm ERR! Move it away, and try again.
```

We're using `node` v8.7.0 and `npm` v5.5.1 on macOS.

Is this something we have done wrong when we implemented Alfy into `alfred-packagist`? What is your thoughts on this issue?

**Comment by SamVerschueren** [comment]
This is why I don't like npm@5. It's full of bugs like these.

https://github.com/npm/npm/issues/11894

**Comment by juandaco** [comment]
I have a similar issue with [alfred-npms](https://github.com/sindresorhus/alfred-npms).

**Comment by SamVerschueren** [comment]
If you read the thread I linked, you will see that this has nothing to do with Alfy. This bug occurs because of the way npm@5 works, buggy... So as long as you use npm@5, it will happen with every Alfred workflow.

**Comment by vinkla** [comment]
This seems to be working in the latest version of Node (v8.9.2) and npm (5.6.0).
