### ISSUE TITLE
Error: Alfred preferences not found at location

### ISSUE THREAD

**Issue by velocityzen** [sindresorhus/alfy#81]
Tried:
`npm install --global alfred-npms`

Got:
```
> alfred-npms@1.1.0 postinstall /usr/local/lib/node_modules/alfred-npms
> alfy-init

{ Error: Command failed: alfred-link
Error: Alfred preferences not found at location /Users/velocityzen/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist
    at pathExists.then.exists (/usr/local/lib/node_modules/alfred-npms/node_modules/resolve-alfred-prefs/index.js:15:10)
    at <anonymous>

    at Promise.all.then.arr (/usr/local/lib/node_modules/alfred-npms/node_modules/execa/index.js:201:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'Error: Alfred preferences not found at location /Users/velocityzen/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n    at pathExists.then.exists (/usr/local/lib/node_modules/alfred-npms/node_modules/resolve-alfred-prefs/index.js:15:10)\n    at <anonymous>\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link',
  timedOut: false }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alfred-npms@1.1.0 postinstall: `alfy-init`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alfred-npms@1.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/velocityzen/.npm/_logs/2018-03-01T04_44_12_239Z-debug.log
```

My preferences file is in dropbox for synchronization.

**Comment by SamVerschueren** [comment]
Do you use Alfred 3?

**Comment by velocityzen** [comment]
Yes!


A.

**Comment by velocityzen** [comment]
It's working now 🤷‍♂️
